version: '3'
services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama

# เผื่อไม่มี ollama (ปัจจุบันใช้แบบ run compose ด้านนอก)